#cloud-config
package_update: true
package_upgrade: true

packages:
  - nginx
  - azure-cli
  - curl

write_files:
  - path: /etc/nginx/sites-available/default
    content: |
      server {
          listen 80 default_server;
          listen [::]:80 default_server;
          
          # Health check endpoint
          location /health {
              access_log off;
              return 200 "healthy\n";
              add_header Content-Type text/plain;
              # Security headers for health endpoint
              add_header X-Content-Type-Options nosniff always;
              add_header X-Frame-Options DENY always;
              add_header X-XSS-Protection "1; mode=block" always;
          }

          # Redirect HTTP to HTTPS
          return 301 https://$host$request_uri;
      }
      
      server {
          listen 443 ssl default_server;
          listen [::]:443 ssl default_server;
          
          # Self-signed SSL certificate
          ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
          ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
          
          # SSL configuration
          ssl_protocols TLSv1.2 TLSv1.3;
          ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384;
          ssl_prefer_server_ciphers off;
          
          root /var/www/html;
          index index.html;

          # Security headers
          add_header X-Content-Type-Options nosniff always;
          add_header X-Frame-Options DENY always;
          add_header X-XSS-Protection "1; mode=block" always;
          add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
          add_header Referrer-Policy "strict-origin-when-cross-origin" always;
          add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';" always;
          
          location / {
              try_files $uri $uri/ =404;
          }
          
          # Health check endpoint
          location /health {
              access_log off;
              return 200 "healthy\n";
              add_header Content-Type text/plain;
              # Security headers for health endpoint
              add_header X-Content-Type-Options nosniff always;
              add_header X-Frame-Options DENY always;
              add_header X-XSS-Protection "1; mode=block" always;
          }
          }
      }

runcmd:
  - systemctl enable nginx
  - systemctl start nginx
  
  # Generate self-signed SSL certificate
  - openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj "/C=US/ST=State/L=City/O=Organization/CN=localhost"
  
  # Download web content from storage
  - mkdir -p /var/www/html
  - az storage blob download --account-name ${storage_account_name} --account-key ${storage_account_key} --container-name web-content --name index.html --file /var/www/html/index.html
  
  # Set proper permissions
  - chown -R www-data:www-data /var/www/html
  - chmod -R 755 /var/www/html
  
  # Restart nginx to apply SSL configuration
  - systemctl restart nginx
  
  # Enable firewall and allow only necessary ports
  - ufw --force enable
  - ufw allow 22/tcp
  - ufw allow 80/tcp
  - ufw allow 443/tcp